package com.miaoshaproject.miaoshaproject.dao;

import com.miaoshaproject.miaoshaproject.dataobject.OrderInfoVO;
import com.miaoshaproject.miaoshaproject.dataobject.OrderInfoVOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    long countByExample(OrderInfoVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int deleteByExample(OrderInfoVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int insert(OrderInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int insertSelective(OrderInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    List<OrderInfoVO> selectByExample(OrderInfoVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    OrderInfoVO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderInfoVO record, @Param("example") OrderInfoVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int updateByExample(@Param("record") OrderInfoVO record, @Param("example") OrderInfoVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int updateByPrimaryKeySelective(OrderInfoVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Mar 14 20:51:49 CST 2019
     */
    int updateByPrimaryKey(OrderInfoVO record);
}