package com.miaoshaproject.miaoshaproject.dao;

import com.miaoshaproject.miaoshaproject.dataobject.SequenceDO;
import com.miaoshaproject.miaoshaproject.dataobject.SequenceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    long countByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int deleteByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    List<SequenceDO> selectByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") SequenceDO record, @Param("example") SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int updateByExample(@Param("record") SequenceDO record, @Param("example") SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Mar 14 09:59:53 CST 2019
     */
    int updateByPrimaryKey(SequenceDO record);

    SequenceDO getSequenceByName(String name);
}